version: '3'

services:
  demopayments:
    image: demopayments:dev
    build:
      args:
        source: obj/Docker/empty/
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\Tom\Source\Repos\DemoPayments\DemoPayments:/app
      - C:\Users\Tom\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Users\Tom\vsdbg:/remote_debugger:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  bin/Debug/netcoreapp2.0/DemoPayments.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
